require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DailyStatementsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DailyStatement. As you add validations to DailyStatement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DailyStatementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all daily_statements as @daily_statements" do
      daily_statement = DailyStatement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:daily_statements)).to eq([daily_statement])
    end
  end

  describe "GET #show" do
    it "assigns the requested daily_statement as @daily_statement" do
      daily_statement = DailyStatement.create! valid_attributes
      get :show, {:id => daily_statement.to_param}, valid_session
      expect(assigns(:daily_statement)).to eq(daily_statement)
    end
  end

  describe "GET #new" do
    it "assigns a new daily_statement as @daily_statement" do
      get :new, {}, valid_session
      expect(assigns(:daily_statement)).to be_a_new(DailyStatement)
    end
  end

  describe "GET #edit" do
    it "assigns the requested daily_statement as @daily_statement" do
      daily_statement = DailyStatement.create! valid_attributes
      get :edit, {:id => daily_statement.to_param}, valid_session
      expect(assigns(:daily_statement)).to eq(daily_statement)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DailyStatement" do
        expect {
          post :create, {:daily_statement => valid_attributes}, valid_session
        }.to change(DailyStatement, :count).by(1)
      end

      it "assigns a newly created daily_statement as @daily_statement" do
        post :create, {:daily_statement => valid_attributes}, valid_session
        expect(assigns(:daily_statement)).to be_a(DailyStatement)
        expect(assigns(:daily_statement)).to be_persisted
      end

      it "redirects to the created daily_statement" do
        post :create, {:daily_statement => valid_attributes}, valid_session
        expect(response).to redirect_to(DailyStatement.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved daily_statement as @daily_statement" do
        post :create, {:daily_statement => invalid_attributes}, valid_session
        expect(assigns(:daily_statement)).to be_a_new(DailyStatement)
      end

      it "re-renders the 'new' template" do
        post :create, {:daily_statement => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested daily_statement" do
        daily_statement = DailyStatement.create! valid_attributes
        put :update, {:id => daily_statement.to_param, :daily_statement => new_attributes}, valid_session
        daily_statement.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested daily_statement as @daily_statement" do
        daily_statement = DailyStatement.create! valid_attributes
        put :update, {:id => daily_statement.to_param, :daily_statement => valid_attributes}, valid_session
        expect(assigns(:daily_statement)).to eq(daily_statement)
      end

      it "redirects to the daily_statement" do
        daily_statement = DailyStatement.create! valid_attributes
        put :update, {:id => daily_statement.to_param, :daily_statement => valid_attributes}, valid_session
        expect(response).to redirect_to(daily_statement)
      end
    end

    context "with invalid params" do
      it "assigns the daily_statement as @daily_statement" do
        daily_statement = DailyStatement.create! valid_attributes
        put :update, {:id => daily_statement.to_param, :daily_statement => invalid_attributes}, valid_session
        expect(assigns(:daily_statement)).to eq(daily_statement)
      end

      it "re-renders the 'edit' template" do
        daily_statement = DailyStatement.create! valid_attributes
        put :update, {:id => daily_statement.to_param, :daily_statement => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested daily_statement" do
      daily_statement = DailyStatement.create! valid_attributes
      expect {
        delete :destroy, {:id => daily_statement.to_param}, valid_session
      }.to change(DailyStatement, :count).by(-1)
    end

    it "redirects to the daily_statements list" do
      daily_statement = DailyStatement.create! valid_attributes
      delete :destroy, {:id => daily_statement.to_param}, valid_session
      expect(response).to redirect_to(daily_statements_url)
    end
  end

end
